//Account
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'; // ACCOUNT_AUTHENTICATE
export const USER_AUTHENTICATE_ERROR = 'USER_AUTHENTICATE_ERROR'; // ACCOUNT_AUTHENTICATE_ERROR
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS'; // ACCOUNT_AUTHENTICATE_SUCCESS
export const USER_LOGOUT = 'USER_LOGOUT'; // ACCOUNT_LOGOUT
