export const ACCOUNT_DETAILS_GET = 'ACCOUNT_DETAILS_GET';
export const ACCOUNT_DETAILS = 'ACCOUNT_DETAILS';
export const ACCOUNT_DETAILS_UPDATE = 'ACCOUNT_DETAILS_UPDATE';
export const ACCOUNT_DETAILS_DELETE = 'ACCOUNT_DETAILS_DELETE';