//Account
export const ACCOUNT_AUTHENTICATE = 'ACCOUNT_AUTHENTICATE'; // ACCOUNT_AUTHENTICATE
export const ACCOUNT_AUTHENTICATE_ERROR = 'ACCOUNT_AUTHENTICATE_ERROR'; // ACCOUNT_AUTHENTICATE_ERROR
export const ACCOUNT_AUTHENTICATE_SUCCESS = 'ACCOUNT_AUTHENTICATE_SUCCESS'; // ACCOUNT_AUTHENTICATE_SUCCESS
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT'; // ACCOUNT_LOGOUT
export const ACCOUNT_INPUT = 'ACCOUNT_INPUT'; // ACCOUNT_INPUT

//Character
export const CHARACTER_LOGIN = 'CHARACTER_LOGIN'; //CHARACTER_LOGIN
export const CHARACTER_LOGOUT = 'CHARACTER_LOGOUT'; //CHARACTER_LOGOUT
export const CHARACTER_ONLINE = 'CHARACTER_ONLINE'; //CHARACTER_LOGIN
export const CHARACTER_OFFLINE = 'CHARACTER_OFFLINE'; //CHARACTER_OFFLINE

export const CHARACTER_LIST = 'CHARACTER_LIST'; //CHARACTER_LIST
export const CHARACTER_GET_LIST = 'CHARACTER_GET_LIST'; //CHARACTER_GET_LIST

export const CHARACTER_CREATE_ERROR = 'CHARACTER_CREATE_ERROR'; //CHARACTER_CREATE_ERROR
export const CHARACTER_CREATE_SUCCESS = 'CHARACTER_CREATE_SUCCESS'; //CHARACTER_CREATE_SUCCESS
export const CHARACTER_UPDATE = 'CHARACTER_UPDATE'; //CHARACTER_UPDATE
export const CHARACTER_DELETE = 'CHARACTER_DELETE'; //CHARACTER_DELETE
export const CHARACTER_DESTINATION = 'CHARACTER_DESTINATION'; //CHARACTER_DESTINATION

//Notes
export const GET_NOTES = 'GET_NOTES'; //GET_NOTES

//Server
export const SERVER_EVENT = 'SERVER_EVENT'; //SERVER_EVENT
